name: Release Windows Debug

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenSSL and InnoSetup and zip
        run: |
          choco install openssl --no-progress
          choco install innosetup --no-progress
          choco install zip --no-progress

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build for Windows
        run: flutter build windows --debug

      - name: Package as exe
        run: iscc innosetup/setup-debug.iss

      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: guet-toolbox-debug.exe
          path: innosetup/output/debug/guet-toolbox.exe

      - name: Package as zip
        run: |
          cd build/windows/runner
          zip -q -r -j ./guet-toolbox-windows-debug.zip Debug
          cd ../../../

      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: guet-toolbox-windows-debug.zip
          path: build/windows/runner/guet-toolbox-windows-debug.zip