name: Release Windows Debug

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check OpenSSL
        run: |
#          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install openssl

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      #      - name: Setup Visual Studio
      #        uses: microsoft/setup-visualstudio@v1
      #        with:
      #          vs-version: '2022'



      - name: Build for Windows
        run: flutter build windows --debug

      - name: Package as MSIX
        run: |
          flutter pub run msix:create --debug
          n

      - name: Upload MSIX artifact
        uses: actions/upload-artifact@v2
        with:
          name: guettoolbox-debug.msix
          path: build/windows/runner/Debug/guettoolbox.msix